# Generated by Django 5.0.7 on 2024-08-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_video', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('descricao', models.TextField()),
                ('data_agendada', models.DateTimeField()),
                ('rede_social', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('postado', 'Postado')], default='agendado', max_length=10)),
            ],
        ),
    ]
