# Generated by Django 5.0.7 on 2024-08-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        ('publicacao', '0002_redesocial_remove_publicacao_rede_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil'),
        ),
    ]
