# Generated by Django 5.0.7 on 2024-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0006_alter_publicacao_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Postado', 'Postado')], default='agendado', max_length=10),
        ),
    ]
