# Generated by Django 5.0.7 on 2024-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0007_alter_publicacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Postado', 'Postado')], default='Agendado', max_length=10),
        ),
    ]
