# Generated by Django 5.0.7 on 2024-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_perfil_rede_social'),
        ('publicacao', '0008_publicacao_post_id_alter_publicacao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='perfil',
        ),
        migrations.AddField(
            model_name='publicacao',
            name='perfil',
            field=models.ManyToManyField(to='perfil.perfil'),
        ),
    ]
