# Generated by Django 5.0.7 on 2024-09-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacao', '0010_alter_publicacao_foto_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
