# Generated by Django 5.0.7 on 2024-10-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0017_alter_perfil_pais'),
        ('publicacao', '0011_alter_publicacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='RegistroPostagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
            ],
        ),
    ]
