# Generated by Django 5.0.7 on 2024-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('rede_social', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=50)),
            ],
        ),
    ]
