# Generated by Django 5.0.7 on 2024-08-16 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_rede_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='login',
            new_name='page_id',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='password',
            new_name='token',
        ),
    ]
