# Generated by Django 5.0.7 on 2024-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_rename_login_perfil_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
