# Generated by Django 5.0.7 on 2024-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_perfil_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
