# Generated by Django 5.0.7 on 2024-08-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_perfil_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='app_id',
            field=models.CharField(blank=True, default=True, max_length=255),
        ),
    ]
