# Generated by Django 5.0.7 on 2024-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_perfil_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='app_id',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
