# Generated by Django 5.0.7 on 2024-08-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_perfil_app_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='app_secret',
            field=models.CharField(max_length=255),
        ),
    ]
