# Generated by Django 5.0.7 on 2024-08-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_alter_perfil_app_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rede_social',
        ),
    ]
