# Generated by Django 5.0.7 on 2024-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_remove_perfil_rede_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rede_social',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='FACEBOOK', max_length=50),
        ),
    ]
