# Generated by Django 5.0.7 on 2024-08-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_perfil_rede_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rede_social',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='Facebook', max_length=50),
        ),
    ]
