# Generated by Django 5.0.7 on 2024-10-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0017_alter_perfil_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao_Bau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_video', models.FileField(blank=True, max_length=120, null=True, upload_to='uploads/publicacao/')),
                ('descricao', models.TextField()),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.perfil')),
            ],
        ),
    ]
